name: Run Integration Tests

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.8.x"]
        # TODO: change to 1.0.1 when available
        dbt: ["0.20.1", "0.21.1", "1.0.1rc1"]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Fix jinja
        run: |
          pip install markupsafe==2.0.1

      - name: Install fal
        run: |
          pip install fal

      - name: Install dbt
        run: |
          if [[ '${{ matrix.dbt }}' =~ ^0.*$ ]]
          then
            pip install dbt==${{ matrix.dbt }}
          else
            pip install dbt-postgres==${{ matrix.dbt }}
          fi

      - name: Install dbt packages
        run: |
          dbt deps

      - name: Setup packages
        run: |
          mkdir integration_tests/mock/dbt_packages
          cp -r dbt_packages/dbt_utils integration_tests/mock/dbt_packages/
          mkdir integration_tests/mock/dbt_packages/feature_store
          cp -r dbt_project.yml macros models packages.yml integration_tests/mock/dbt_packages/feature_store

      - name: Start test Docker database
        working-directory: integration_tests
        run: docker-compose up -d

      - name: Install test dependencies
        working-directory: integration_tests/mock
        run: |
          pip install behave
          (test -f requirements.txt && pip install -r requirements.txt) || echo "No requirements.txt"

      - name: Run integration tests
        working-directory: integration_tests
        env:
          FAL_STATS_ENABLED: false
        run: behave
